name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.7.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_app_badger: ^1.3.0
  flutter:
    sdk: flutter
  stream_chat_flutter: ^3.0.0
  stream_chat_persistence: ^3.0.0
  stream_chat_localizations: ^3.0.0
  flutter_local_notifications: ^9.0.0
  flutter_svg: ^0.23.0
  flutter_secure_storage: ^4.2.1
  yaml: ^3.1.0
  uuid: ^3.0.5
  streaming_shared_preferences: ^2.0.0
  lottie: ^1.2.1
  collection: ^1.15.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  test: any

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
